gallery/gallery/urls.py
from django.contrib.auth.views import logout_then_login
from django.conf.urls import include, url
from django.contrib import admin


from app.views import *
from app.ajax import *


urlpatterns = [
    url(r'^admn/grappelli/', include('grappelli.urls')),
    url(r'^admn/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admn/', include(admin.site.urls)),
    url(r'^$', AppLoginView.as_view(), name="login"),
    url(r'^logout/$', lambda request: logout_then_login(request, "/"), name="logout"),
    url(r'^albums/$', AlbumsPage.as_view(), name='main'),
    url(r'^albums/(?P<album_pk>\d+)/$', AlbumPage.as_view(), name='album'),
    url(r'^albums/upload', UploadPage.as_view(), name='upload'),
    url(r'^albums/setting/(?P<album_pk>\d+)/$', AlbumSettingPage.as_view(), name='album_setting'),
    url(r'^api/albums/create', create_album, name='create_album'),
    url(r'^api/album/cover/(?P<album_pk>\d+)/$', cover_set, name="cover_set"),
    url(r'^api/album/upload/(?P<album_pk>\d+)/$', upload_album, name='upload_album'),
    url(r'^api/photo/upload/(?P<album_pk>\d+)/$', upload_photo, name='upload_photo'),
    url(r'^api/setting/(?P<album_pk>\d+)/$', save_setting, name='save_setting'),
    url(r'^api/photo/delete', delete_photo, name='delete_photo'),
    url(r'^api/user/create', create_user, name='create_user'),
    url(r'^api/user/info/(?P<user_pk>\d+)/$', info_user, name='info_user'),
    url(r'^api/user/save/(?P<user_pk>\d+)/$', save_user, name='save_user'),
    url(r'^api/download/photo/(?P<photo_pk>\d+)/$', download_photo, name='download_photo'),
    url(r'^adm/$', AdminDashboardView.as_view(), name="admin_dashboard"),
]

gallery/app/models.py
# coding: utf-8

import os
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from nnmware.core.abstract import AbstractName, AbstractDate
from nnmware.core.models import NnmwareUser
from nnmware.core.imgutil import remove_thumbnails, remove_file

class GalleryUser(NnmwareUser):
    read_only = models.BooleanField(verbose_name=_('Read only user'), blank=True, default=False)


class GalleryAlbum(AbstractDate, AbstractName):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, verbose_name=_("Author"))
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name=_('Users'),
                                   related_name='album_users')
    class Meta:
        ordering = ['name']
        verbose_name = _('Album')
        verbose_name_plural = _('Albums')

    def get_absolute_url(self):
        return reverse('main', kwargs={'pk': self.pk})


def get_image_path(instance, filename):
    instance.title = str(filename)[:-4]
    return "photofile/%s/%s" % (instance.album.pk, filename)


@python_2_unicode_compatible
class GalleryPhoto(models.Model):
    album = models.ForeignKey(GalleryAlbum)
    image = models.ImageField(verbose_name=_('Photo'), upload_to=get_image_path)
    title = models.CharField(verbose_name=_('Title photo'), max_length=255, blank=True, default='')

    class Meta:
        ordering = ['title']
        verbose_name = _('Photo')
        verbose_name_plural = _('Photos')

    def __str__(self):
        return _("%s") % self.title

    def delete(self, *args, **kwargs):
        try:
            remove_thumbnails(self.image.path)
            remove_file(self.image.path)
        except:
            pass
        super(GalleryPhoto, self).delete(*args, **kwargs)

gallery/app/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model, authenticate

from nnmware.core.exceptions import UserIsDisabled

from models import GalleryAlbum


class AppLoginForm(forms.Form):
    username = forms.CharField(label=_('Username'), max_length=30)
    password = forms.CharField(label=_('Password'), max_length=30)

    class Meta:
        widgets = dict(password=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data["username"]
        if not username:
            raise forms.ValidationError(_("Username is required"), code='invalid')
        try:
            user = get_user_model().objects.get(username=username)
            if not user.is_active:
                raise UserIsDisabled
            return username
        except get_user_model().DoesNotExist:
            raise forms.ValidationError(_("Username not exist"), code='invalid')
        except UserIsDisabled:
            raise forms.ValidationError(_("User is disabled"), code='invalid')

    def clean_password(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError(_("Password is incorrect"), code='invalid')
        return password

gallery/app/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth import get_user_model, authenticate, login
from django.views.generic import FormView
from django.views.generic import TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import ListView
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from nnmware.core.views import AjaxFormMixin, CurrentUserSuperuser

from forms import AppLoginForm
from models import GalleryAlbum, GalleryPhoto


class AuthCheckMixin(object):
    """check whether the user is logged
    in when you click on the direct url"""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/')
        return super(AuthCheckMixin, self).dispatch(request, *args, **kwargs)


class AppLoginView(AjaxFormMixin, FormView):
    form_class = AppLoginForm
    success_url = "albums/"
    template_name = 'login.html'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(AppLoginView, self).form_valid(form)


class AlbumsPage(AuthCheckMixin, ListView):
    template_name = 'albums.html'
    context_object_name = "albums"

    def get_queryset(self):
        if self.request.user.is_superuser:
            result_list = GalleryAlbum.objects.all
        else:
            result_list = GalleryAlbum.objects.filter(users=self.request.user)
        return result_list


class AlbumPage(AuthCheckMixin, SingleObjectMixin, ListView):
    template_name = 'album.html'

    def get_object(self, queryset=None):
        return get_object_or_404(GalleryAlbum, pk=int(self.kwargs['album_pk']))

    def get_queryset(self):
        self.object = self.get_object()
        return GalleryPhoto.objects.filter(album=self.object)


class UploadPage(AuthCheckMixin, TemplateView):
    template_name = 'upload.html'


class AlbumSettingPage(AuthCheckMixin, SingleObjectMixin, ListView):
    template_name = 'album_setting.html'

    def get_object(self, queryset=None):
        return get_object_or_404(GalleryAlbum, pk=int(self.kwargs['album_pk']))

    def get_queryset(self):
        self.object = self.get_object()
        return GalleryPhoto.objects.filter(album=self.object)

class AdminDashboardView(CurrentUserSuperuser, ListView):
    template_name = 'admin/admin.html'

    def get_queryset(self):
        return get_user_model().objects.all()

gallery/templates/album.html
{% extends 'main.html' %}

{% load static core %}

{% block title %}{{ object.name }}{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'plugins/fancybox/jquery.fancybox.css' %}"/>
    <script src="{% static 'plugins/fancybox/jquery.fancybox.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#settings').css('display', 'block');
            $('#setting_link').attr('href', "{% url 'album_setting' object.pk %}");
            $('.album_name').text("{{ object.name }}");
            $('#count-photo').text("(total photo: {{ object_list.count }})");
	        $(".fancybox").fancybox({
		        openEffect	: 'none',
		        closeEffect	: 'none'
	        });
        });
    </script>
{% endblock %}

{% block content %}
<div id="content_photo">
    {% if object %}
        <div id="description">
            <p>{{ object.description }}</p>
        </div>
        {% for photo in object_list %}
            <div class="photo">
                <a class="fancybox" rel="gallery1" href="{{ photo.image.url|thumbnail:"width=1280,height=960" }}" title="{{ photo.title }}">
	                <img class="img-gray" src="{{ photo.image.url|thumbnail:"width=238,height=178" }}" title="{{ photo.title }}" />
                </a>
                <a href="{% url 'download_photo' photo.pk %}"><div id="download"></div></a>
            </div>
        {% endfor %}
    {% else %}
        <h1 class="nothing">Sorry, no data in this section</h1>
    {% endif %}
</div>
{% endblock %}

gallery/templates/album_cover.html
{% load static %}

<div id="upload_div" style="display:none"></div>
<div id="album-cover" style="display: none">
    {% if object.img %}
        <img id="cover-place" alt="" src="{{ object.img.url }}"/>
    {% else %}
        <img id="cover-place" alt="" src="{% static 'images/no_cover.png' %}"/>
    {% endif %}
    <span id="cover-uploader" onclick="">Click for upload cover</span>
</div>

gallery/templates/album_setting.html
{% extends 'main.html' %}

{% load static core app %}

{% block title %}Album setting{% endblock %}

{% block head %}
    <script src="{% static 'js/api.js' %}"></script>
    <script src="{% static 'js/fineuploader.min.js' %}" type="text/javascript"></script>
{% endblock %}

{% block script %}
{% include 'image_upload.html' %}
    <script>
        $(document).ready(function() {
            $('.album_name').text("{{ object.name }}");
            $('#button-save').on('click', function(e){
                e.preventDefault();
                var form = $(this).closest('form');
                $.post("{% url 'save_setting' object.pk %}", form.serialize(),function(data) {
                    if (data.success == true) {
                        $('.album_name').text(data.name);
                        alert(data.name + ' saved album!')
                    }
                    else {
                        alert(data.error);
                    }
                });
            });
            $('#button-delete').on('click', function(e){
                if (confirm('Delete select photo?')) {
                    e.preventDefault();
                    var form = $(this).closest('form');
                    $.post("{% url 'delete_photo' %}", form.serialize(),function(data) {
                        if (data.success == true) {
                           window.location.reload();
                        }
                    });
                }
            });
            AlbumUploadPhoto({{ object.pk }});
        });
    </script>
{% endblock %}

{% block content %}
    {% if user.is_superuser or user == object.user %}
        <table id="table-1">
            <tr>
                <td id="td-1">
                    {% include 'album_cover.html' %}
                    <div id="info">
                        <p><span><strong>Author: </strong>{{ object.user }}</span></p>
                        <p><span><strong>Created date: </strong>{{ object.created_date }}</span></p>
                        <p><span><strong>Total photo: </strong>{{ object_list.count }}</span></p>
                    </div>
                </td>
                <td id="td-21">
                    <div id="album-info">
                        <form>
                            <div id="info-left">
                                {% csrf_token %}
                                <p>Title album: <input id="input-title-album" class="input-upload" type="text" name="album_name" value="{{ object.name }}"></p>
                                <p>Description:</p>
                                <textarea class="input-upload" name="comment" cols="40" rows="3">{{ object.description }}</textarea>
                                <input type="submit" name="save-setting" id="button-save" class="input-upload" value="Save">
                            </div>
                            <div id="info-right">
                                {% if user.is_superuser %}
                                    <p>Users:</p>
                                    <ul>
                                    {% all_users as users %}
                                    {% for item in users %}
                                        <li>
                                        {% if item in object.users.all %}
                                            <label><input type="checkbox" name="users" checked value="{{ item.pk }}"><span>{{ item }}</span></label><br>
                                        {%  else %}
                                            <label><input type="checkbox" name="users" value="{{ item.pk }}"><span>{{ item }}</span></label><br>
                                        {%  endif %}
                                        </li>
                                    {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </td>
            </tr>
            <tr>
            <td colspan="2">
                <div id="album_photos">
                    <form>
                        {% csrf_token %}
                        {% for item in object_list %}
                            <label>
                                <input id="photo" name="photo" type="checkbox" value="{{ item.pk }}" style="display: none" >
                                <img src="{{ item.image.url|thumbnail:"width=238,height=178" }}" alt="{{ item.title }}">
                            </label>
                        {% endfor %}
                        <br>
                        {% if user.is_superuser or user == object.user %}
                            <input type="submit" name="delete_photo" id="button-delete" class="input-upload" value="Delete photo">
                        {% endif %}
                    </form>
                </div>
            </td>
            </tr>
        </table>
    {% else %}
        <h1 class="nothing">Sorry, no data in this section</h1>
    {% endif %}
{% endblock %}

gallery/templates/albums.html
{% extends 'main.html' %}

{% load static core %}

{% block title %}Albums{% endblock %}

{% block header %}{% endblock %}

{% block content %}

<div id="content_albums">
    {% if object_list %}
        {% for album in albums %}
            <div class="cell">
                <div class="album">
                    <div class="cover">
                        <a href="{{ album.pk }}">
                            {% if album.img %}
                                <img class="img-gray" src="{{ album.img.url }}" alt="{{ album.name }}" />
                            {% else %}
                                <img src="{% static 'images/no_cover.png' %}" alt="No cover" />
                            {%  endif %}
                        </a>
                    </div>
                    <div id="total-photo"><strong>{{ album.galleryphoto_set.count }}</strong></div>
                    <p>{{ album.name }}</p>
                </div>

            </div>
        {% endfor %}
    {% else %}
        <h1 class="nothing">Sorry, no data in this section</h1>
    {% endif %}
</div>

{% endblock %}

gallery/templates/header.html
{% load static core app %}

<div id="header">
        <div class="head-menu-left">
            <div class="text_span">
                <a href='{% url 'main' %}'>
                    <span class="home">Albums</span>
                </a>
            </div>
        </div>
        <div class="head-menu-center">
            <ul>
                <li>
                    <div id="upload" class="head-icon">
                        {% if not user.read_only %}
                            <a href="{% url 'upload' %}">
                                <img src="{{ STATIC_URL }}images/upload.png" title="Upload photo" width="24" height="24" />
                            </a>
                        {% endif %}
                    </div>
                </li>
                <li>
                    <div id="settings" class="head-icon" style="display: none">
                        {% if user.is_superuser or user == object.user %}
                            <a id="setting_link" href="">
                                <img src="{%  static 'images/settings.png' %}" width="24" height="24" title="Album settings" />
                            </a>
                        {% endif %}
                    </div>
                </li>
                <li>
                    <div class="text_span">
                        <a href="" id="album_link">
                            <span class="album_name"></span>
                        </a>
                    </div>
                </li>
                <li>
                    <div class="text_span">
                        <span id="count-photo"></span>
                    </div>
                </li>
            </ul>
        </div>
        <div class="head-menu-right">
            <div id="admin" class="text_span">
                {% if user.is_superuser %}
                    <a href="{% url 'admin_dashboard' %}"><span>admin</span></a>
                {% endif %}
            </div>
            <div id="acount">
                <span class="welcome">Welcome,</span>
	            <span>{{ user.username }}</span>
            </div>
            <div id="logout" class="head-icon">
                <a class="unlock" href="{% url 'logout' %}"></a>
            </div>
        </div>
</div>

gallery/templates/image_upload.html
{% load core static %}

<script>
var uploader_cover = {};
var uploader_photo = {};
window.onload = function () {
    uploader_cover = new qq.FineUploaderBasic({
        multiple: false,
        debug: false,
        sizeLimit: 10485760,
        button: $('#upload_div')[0],
        validation: {
            allowedExtensions: ['jpeg', 'jpg']
        },
        callbacks: {
            onComplete: function (id, fileName, data) {
                if (data.success) {
                    var a = $(data.html).find('img').attr('src');
                    $('#cover-place').attr('src', a);
                }
            }
        }
    });
    uploader_photo = new qq.FineUploader({
        element: document.getElementById('fine-uploader'),
        autoUpload: false,
        maxConnections: 1,
        editFilename: {
            enabled: true
        },
        validation: {
            allowedExtensions: ['jpeg', 'jpg']
        },
        callbacks: {
            onError: function (id, fileName, error) {
                    alert(qq.format("Error on file {} - {}", fileName, error));
            }
        }
    });
};
function AjaxCoverUpload(path) {
	uploader_cover.setEndpoint(path);
    var params = {'csrfmiddlewaretoken': '{{ csrf_token }}'};
    uploader_cover.setParams(params);
	$('input[type=file]','#upload_div').click();
}
function AlbumUploadPhoto(pk) {
    $('#album-cover').css('display', 'block');
    $('#upload_photo').css('display', 'block');
    var link = '/api/album/upload/' + pk + '/';
    $.post(link, {'album_pk': pk}, function(data) {
        if (data.success) {
            $('.album_name').text(data.name);
            var f = "AjaxCoverUpload('/api/album/cover/" + pk + "/'); return false;";
            $('#cover-uploader').attr('onclick', f);
            var a = $(data.html).find('img').attr('src');
            $('#cover-place').attr('src', a);
            $('#album_link').attr('href', '/albums/' + pk + '/');
        }
    });
    qq(document.getElementById("edit-file-upload-trigger")).attach("click", function() {
        var url_path = '/api/photo/upload/' + pk + '/';
        uploader_photo.setEndpoint(url_path);
        var params = {'csrfmiddlewaretoken': '{{ csrf_token }}'};
        uploader_photo.setParams(params);
        uploader_photo.uploadStoredFiles();
    });
}
</script>

gallery/templates/index.html
{% load static %}

<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css" media="all" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/api.js' %}"></script>
    {% block head %}{% endblock %}
    {% block script %}{% endblock %}
</head>
<body>
    {% block login %}{% endblock %}
</body>
</html>

gallery/templates/login.html
{% extends "index.html" %}

{% block title %}Login{% endblock %}

{% block login %}
<div id="gallery-modalbox">
    <script>
         $(document).ready(function() {
             $('a.lock').on('click', function (e) {
                 e.stopImmediatePropagation();
                 e.preventDefault();
                 $('body').addClass('modal-open');
                 $('a.account_login').click();
                 $('#gallery-modalbox').show();
                 $('.login').css('display', 'none');
                 $(document).keyup(function (e) {
                     if (e.keyCode == 27) {
                         $('body').removeClass('modal-open');
                         $('#gallery-modalbox').hide();
                         $('.login').css('display', 'block');
                         $(document).unbind('keyup');
                     }
                 });
             });
             $('.login-btn').on('click', function (e) {
                 e.stopImmediatePropagation();
                 e.preventDefault();
                 if ($(this).hasClass('recover')) {
                     var recover = true;
                 }
                 var form = $(this).closest('form');
                 $.post(form.attr('action'), form.serialize(), function (data) {
                     if (data.success) {
                         if (recover) {
                             var status = form.find('.gallery-modal-status');
                             status.css('display', 'block').html(data.status_msg);
                             setTimeout(function () {
                                 status.css('display', 'none').html('');
                             }, 4000);
                         }
                         else {
                             window.location.replace(data.location);
                         }
                     }
                     else {
                         AjaxFormError(data.data, form);
                     }
                 });
             });
             $('.gallery-modal').on('click', 'strong', function (e) {
                 e.preventDefault();
                 $('body').removeClass('modal-open');
                 $('#gallery-modalbox').hide();
                 $('.login').css('display', 'block');
             });
             $('a.account_login').on('click', function (e) {
                 e.preventDefault();
                 $('#loginform').show();

             });
         })
    </script>
    <div class="gallery-modal">
        <form id="loginform" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="gallery-modal-header">
                <span>Log in</span>
                <strong>X</strong>
            </div>
            <div class="gallery-modal-inner">
                <div class="gallery-modal-status"></div>
                <input type="text" name="username" placeholder="username" value="" autocomplete="off" />
                <input type="password" name="password" placeholder="password" value="" autocomplete="off" />
            </div>
            <div class="gallery-modal-bottom">
                <input value="Log in&nbsp;»" class="login-btn button button-flat" type="submit" />
            </div>
        </form>
    </div>
</div>
<div class="login">
    <a href="#" class="lock"></a>
</div>
{% endblock %}

gallery/templates/main.html
{% load static %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/api.js' %}"></script>
    <script>
        $("a[href='#top']").click(function() {
            $("html, body").animate({ scrollTop: 0 }, "slow");
            return false;
        });
    </script>
    {% block head %}{% endblock %}
    {% block script %}{% endblock %}
    
</head>
<body>
    {% include 'header.html' %}
    <div id="container">
        {% block content %}{% endblock %}
        <p id="upscroll">
            <a href="#top"><span></span></a>
        </p>
    </div>
    <div id="footer">
    </div>
</body>
</html>

gallery/templates/photo.html
{% extends 'main.html' %}

{% load static core %}

{% block title %}Фотографии{% endblock %}

{% block content %}
    <div>
      <p>PHOTO</p>
      <a href='{{ object.image.url }}'>Original PHOTO</a>

      <img src="{{ object.image.url|thumbnail:"width=800,height=600,aspect=1" }}" alt="{{ object.title }}" />
    </div>
{% endblock %}

gallery/templates/upload.html
{% extends 'main.html' %}

{% load static core app %}

{% block title %}Upload photo{% endblock %}
{% block head %}
    <script src="{% static 'js/api.js' %}"></script>
    <script src="{% static 'js/fineuploader.min.js' %}" type="text/javascript"></script>
{% endblock %}

{% block script %}
{% include 'image_upload.html' %}
<script>
    $(document).ready(function() {
        $('#albums_select').val('choice');
        $('select option').on('click', function(){
            uploader_photo.reset();
            if ($(this).val()== 'create_album')
            {
                document.getElementById('create_album').style.display = 'block';
                document.getElementById('upload_photo').style.display = 'none';
                document.getElementById('album-cover').style.display = 'none';
            }
            else if ($(this).val()== 'choice')
            {
                document.getElementById('create_album').style.display = 'none';
                document.getElementById('upload_photo').style.display = 'none';
                document.getElementById('album-cover').style.display = 'none';
            }
            else
            {
                document.getElementById('create_album').style.display = 'none';
                AlbumUploadPhoto($('#albums_select option:selected').val());
            }
        });
        $('#button').on('click', function(e){
            e.preventDefault();
            var form = $(this).closest('form');
            $.post("{% url 'create_album' %}", form.serialize(),function(data) {
                if (data.success) {
                    $('#albums_select').append($("<option></option>").attr("value",data.pk).text(data.name));
                    $('#albums_select').val(data.pk);
                    $('#create_album').css('display', 'none');
                    AlbumUploadPhoto($('#albums_select option:selected').val());
                }
                else {alert(data.error);}
            });
        });
    });
  </script>
{% endblock %}


{% block content %}
    <table id="table-1">
        <tr>
            <td id="td-1">
                {% include 'album_cover.html' %}
            </td>
            <td id="td-2">
                <div class="content-select">
                    <div id="upload_div" style="display:none"></div>
                    {% album_names as albums %}
                    <span>Choice album:</span>
                    <select id="albums_select" name='albums'>
                        <option value="choice" selected>---</option>
                        <option value="create_album">create new album</option>
                        {% for item in albums %}
                            <option value="{{ item.pk }}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div id="create_album" class="content-select" style="display: none">
                    <form>
                        {% csrf_token %}
                        <input type="text" name="album_name" class="input-upload" value="" placeholder="Album name">
                        <input type="submit" name="createalbum" id="button" class="input-upload" value="Create album">
                    </form>
                </div>
                {% include 'upload_photo.html' %}
            </td>
        </tr>
    </table>
{% endblock %}

gallery/templates/upload_photo.html
{% load static %}

<div id="upload_photo" class="content-select" style="display: none">
<div id="fine-uploader"></div>
<div id="edit-file-upload-trigger" class="btn" style="margin-top: 10px;">
    Upload now
</div>

<script type="text/template" id="qq-template">
    <div class="qq-uploader-selector qq-uploader">
        <div class="qq-upload-button-selector qq-upload-button">
            <div>Choice a photo files</div>
        </div>
        <ul class="qq-upload-list-selector qq-upload-list">
            <li>
                <div class="qq-progress-bar-container-selector">
                    <div class="qq-progress-bar-selector qq-progress-bar"></div>
                </div>
                <span class="qq-edit-filename-icon-selector qq-edit-filename-icon"></span>
                <span class="qq-upload-file-selector qq-upload-file"></span>
                <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                <span class="qq-upload-size-selector qq-upload-size"></span>
                <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">Cancel</a>
                <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
            </li>
        </ul>
    </div>
</script>
</div>